select
--a.ARINVOICEID,
--a.USEDINSIID,
--a.USEDINSI,
NULL INVOICENO, --a.INVOICENO,
NULL PONOFROMDO, --a.PONOFROMDO,
a.ITEMNO, a.ITEMOVDESC, SUM(a.QUANTITY) QUANTITY,
a.ITEMDISCPC, a.BRUTOUNITPRICE, a.UNITPRICE,
a.ITEMUNIT, a.UNITRATIO, a.ITEMTYPE,
a.UNIT1, a.UNIT2, a.UNIT3, a.RATIO2, a.RATIO3, a.NOTES,
a.INVENTORYGLACCNT, a.COGSGLACCNT, a.SALESGLACCNT,
a.SALESDISCOUNTACCNT, a.GOODSTRANSITACCNT,
a.TAXCODES, Sum(a.TAXABLEAMOUNT1) TAXABLEAMOUNT1, Sum(a.TAXABLEAMOUNT2) TAXABLEAMOUNT2,
a.ITEMRESERVED1, a.ITEMRESERVED2, a.ITEMRESERVED3,
a.ITEMRESERVED4, a.ITEMRESERVED5, a.ITEMRESERVED6,
a.ITEMRESERVED7, a.ITEMRESERVED8, a.ITEMRESERVED9,
a.ITEMRESERVED10, --a.SOID,
NULL SONO, --a.SONO,
NULL PONOFROMSO, --a.PONOFROMSO,
a.DEPTID, a.DEPTNO, a.DEPTNAME,
a.PROJECTID, a.PROJECTNO, a.PROJECTNAME,
a.WAREHOUSEID, a.NAME WPIName, a.SUMDONO USEDINSI
From TEMPLATE_ARINVDET(:ARINVOICEID, 0) a
Where 1=1
and (a.GroupSeq is null or (a.GroupSeq is not null
and (Exists (select s.Seq from ARINVDET s
inner join Item it on it.itemNo=s.ItemNo and it.ItemType=3
where it.MinimumQty=1 and s.ARInvoiceID=a.ARInvoiceID and s.Seq=a.GroupSeq))))
Group by
--a.ARINVOICEID,
--a.USEDINSIID,
--a.USEDINSI, --a.INVOICENO, a.PONOFROMDO,
a.ITEMNO, a.ITEMOVDESC,
a.ITEMDISCPC, a.BRUTOUNITPRICE, a.UNITPRICE,
a.ITEMUNIT, a.UNITRATIO, a.ITEMTYPE,
a.UNIT1, a.UNIT2, a.UNIT3, a.RATIO2, a.RATIO3, a.NOTES,
a.INVENTORYGLACCNT, a.COGSGLACCNT, a.SALESGLACCNT,
a.SALESDISCOUNTACCNT, a.GOODSTRANSITACCNT,
a.TAXCODES,
a.ITEMRESERVED1, a.ITEMRESERVED2, a.ITEMRESERVED3,
a.ITEMRESERVED4, a.ITEMRESERVED5, a.ITEMRESERVED6,
a.ITEMRESERVED7, a.ITEMRESERVED8, a.ITEMRESERVED9,
a.ITEMRESERVED10, --a.SOID, a.SONO, a.PONOFROMSO,
a.DEPTID, a.DEPTNO, a.DEPTNAME,
a.PROJECTID, a.PROJECTNO, a.PROJECTNAME,
a.WAREHOUSEID, a.NAME, a.SUMDONO
Order by a.ITEMNO